language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

services: mysql

before_install:
  - phantomjs -v
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - git clone -b v1.2-dev --single-branch https://github.com/humhub/humhub.git
  - ls 
  - export HUMHUB_PATH = $HOME

  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - travis_retry composer global require "codeception/codeception=2.1.*" "codeception/specify=*" "codeception/verify=*"

  - |
    mysql -e 'CREATE DATABASE `humhub_test` CHARACTER SET utf8 COLLATE utf8_general_ci;'
    cd protected/humhub/tests/codeception/bin
    php yii migrate/up --includeModuleMigrations=1 --interactive=0
    php yii installer/auto
    php yii search/rebuild
    cd ../../../../..
    cd protected/humhub/tests
    codecept build
    cd ../../../

script:
  - php -S 127.0.0.1:8080 > /dev/null 2>&1 &
  - phantomjs --webdriver=4444 > /dev/null 2>&1 &
  - sleep 5
  - curl http://127.0.0.1:8080/index-test.php
  - |
    cd protected/humhub/tests/
    codecept run

after_failure:
  - ls
  - pwd
  - cd ../modules/user/tests/codeception/_output/
  - ls
  - cat user.functional.LoginCest.testUserLogin.fail.html
  #cat ../modules/*/tests/codeception/_output/*.html
    